springdoc:
  swagger-ui:
    path: / #http://localhost:8080/swagger-ui/index.html#/
    groups-order: ASC #group 정렬
    tags-sorter: alpha #tag 정렬
    operations-sorter: alpha #method - api 정렬
    doc-expansion: none #swagger tag 리스트 펼치기
    disable-swagger-default-url: true
    display-request-duration: true #Try it out 을 실행 후 api 실행 시간표시(milliseconds)
    display-query-params-without-oauth2 : true
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  cache:
    disabled: true
  override-with-generic-response: false
  model-and-view-allowed: true #retrunType ModelAndView에도 Swagger에 노출
  show-actuator: true #엔드포인트
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**

spring:
  profiles:
    default: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/local?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimeZone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '0000'
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: update
    database: mysql

custom:
  jwt:
    secretKey: '8B2743837647E433C551A532977A1ZQ'