springdoc:
  swagger-ui:
    path: /
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true #엔드포인트
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**